In [56]:
import pandas as pd

In [57]:
df = pd.read_csv("data/sample_data.csv")
df.head()

      category                              text
0   Sanitation  Garbage not collected for 3 days
1  Electricity     Street lights are not working
2        Water     No water supply since morning
3        Roads    Big potholes causing accidents
4   Sanitation       Bad smell from garbage area

In [58]:
df.shape

(8, 2)

In [59]:
df.columns

Index(['category', 'text'], dtype='object')

In [60]:
def clean_text(text):
    return text.lower()

In [61]:
df['clean_text']=df['text'].apply(clean_text)

In [62]:
df.head()

,category,text,clean_text
0,Sanitation,Garbage not collected for 3 days,garbage not collected for 3 days
1,Electricity,Street lights are not working,street lights are not working
2,Water,No water supply since morning,no water supply since morning
3,Roads,Big potholes causing accidents,big potholes causing accidents
4,Sanitation,Bad smell from garbage area,bad smell from garbage area

In [63]:
import re

In [64]:
def clean_text(text):
    text = text.lower()
    text = re.sub(r"[^a-zA-Z\s]","",text)
    return text

In [65]:
df['clean_text'] = df['text'].apply(clean_text)

In [66]:
df.head()

,category,text,clean_text
0,Sanitation,Garbage not collected for 3 days,garbage not collected for days
1,Electricity,Street lights are not working,street lights are not working
2,Water,No water supply since morning,no water supply since morning
3,Roads,Big potholes causing accidents,big potholes causing accidents
4,Sanitation,Bad smell from garbage area,bad smell from garbage area

In [67]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

ModuleNotFoundError: No module named 'nltk'